import sqlite3

# open database return conn e cursor
def db():
    conn = sqlite3.connect("./db/stok.db")
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    return conn, cursor

rowInsert = []

rowInsert.append("INSERT INTO categoria (id, descricao, ativo) VALUES (1, 'Celular', 1)")
rowInsert.append("INSERT INTO categoria (id, descricao, ativo) VALUES (2, 'Material de Escritório', 1)")
rowInsert.append("INSERT INTO categoria (id, descricao, ativo) VALUES (3, 'Placa Mãe', 1)")
rowInsert.append("INSERT INTO categoria (id, descricao, ativo) VALUES (4, 'Fone Blutooth', 1)")
rowInsert.append("INSERT INTO categoria (id, descricao, ativo) VALUES (5, 'Teste', 0)")
rowInsert.append("INSERT INTO categoria (id, descricao, ativo) VALUES (6, 'Teclado', 1)")
rowInsert.append("INSERT INTO categoria (id, descricao, ativo) VALUES (7, 'Relógio', 1)")
rowInsert.append("INSERT INTO categoria (id, descricao, ativo) VALUES (8, 'Pendrive', 0)")
rowInsert.append("INSERT INTO categoria (id, descricao, ativo) VALUES (9, 'Mouse', 1)")
rowInsert.append("INSERT INTO categoria (id, descricao, ativo) VALUES (10, 'SSD', 1)")
rowInsert.append("INSERT INTO categoria (id, descricao, ativo) VALUES (11, 'Monitor', 1)")

rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (1, 'Motorola', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (2, 'Samsung', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (3, 'Faber Castel', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (4, 'Gigabyte', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (5, 'QCY', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (6, 'Marca Teste', 0)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (7, 'Asus', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (8, 'Mtek', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (9, 'Satellite', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (10, 'Cassio', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (11, 'Xaiomi', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (12, 'Sandisk', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (13, 'B-Max', 1)")
rowInsert.append("INSERT INTO marca (id, descricao, ativo) VALUES (14, 'Kingston', 1)")

rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (1, 'Celular Edge 40', NULL, '', 'UNI', 10, 10, 5, 100, 700, 750, 730, 0, 1, 1)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (2, 'Celular Samsung A25', NULL, '', 'UNI', 10, 15, 5, 90, 710, 760, 740, 1, 1, 2)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (3, 'Borracha', NULL, '', 'UNI', 10, 10, 5, 100, 3, 5, 4, 1, 2, 3)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (4, 'Celular Edge 50', NULL, '', 'UNI', 10, 10, 5, 100, 653.55, 753.53, 710.25, 1, 1, 2)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (5, 'Caneta Azul', NULL, '', 'UNI', 10, 10, 5, 100, 1, 3, 2, 1, 2, 1)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (6, 'Lápis', NULL, '', 'UNI', 1, 10, 5, 100, 3, 5, 4, 0, 2, 3)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (7, 'Placa Mãe Gigabyte B450', NULL, '', 'UNI', 10, 10, 5, 100, 288.55, 355.5, 335, 1, 3, 4)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (8, 'Fone Blutooth', NULL, '', 'UNI', 10, 10, 5, 100, 23.3, 33.5, 30.5, 1, 4, 5)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (9, 'Produto Teste', NULL, '', 'UNI', 3, 10, 5, 100, 1, 3, 2, 1, 5, 6)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (10, 'Placa Mãe Asus', NULL, '', 'UNI', 10, 10, 5, 100, 370.33, 415.25, 403.4, 1, 3, 7)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (11, 'Pendrive 32GB', NULL, '', 'UNI', 0, 10, 5, 100, 25, 35, 30, 1, 8, 12)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (12, 'Mouse 3 botões', NULL, '', 'UNI', 0, 10, 5, 100, 6, 14, 10, 1, 1, 13)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (13, 'SSD 1GB', NULL, '', 'UNI', 10, 10, 5, 100, 35, 45, 40, 1, 10, 14)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (14, 'Monitor 24 Polegadas', NULL, '', 'UNI', 1, 10, 5, 100, 650, 730, 700, 1, 11, 2)")
rowInsert.append("INSERT INTO produto (id, descricao, imagem, observacao, unidade, qtde, qtde_atacado, estoque_minimo, estoque_maximo, preco_custo, preco_varejo, preco_atacado, ativo, categoria_id, marca_id) VALUES (15, 'Apontador', NULL, '', 'UNI', 6, 10, 5, 100, 5, 8, 7, 1, 2, 3)")

rowInsert.append("INSERT INTO fornecedor (id, nome, razao_social, cnpj, inscricao_estadual, telefone, email, site, observacao, ativo, cep, rua, numero, bairro, cidade, estado, complemento) VALUES (2, 'Distribuidora de Pendrive', 'Distribuidora de Pendrive', '01.154.450/0001-58', '4 5665 456', '41 98826 8276', 'dist@bol.com', '', '', 1, '83430-000', 'Rua Jose Ramos', '113', 'Centro', 'Campina', 'PR', '')")
rowInsert.append("INSERT INTO fornecedor (id, nome, razao_social, cnpj, inscricao_estadual, telefone, email, site, observacao, ativo, cep, rua, numero, bairro, cidade, estado, complemento) VALUES (3, 'Distribuidora de Mouse', 'Rick Distribuidora de Mouse Ltda', '01.124.552/0001-45', '4 456 456 1', '41 9 8826 8276', 'rick@bol.com', 'rick.com.br', '', 0, '83430-000', 'Coronel Monteiro', '122', 'Centro', 'Pinhais', 'PR', '')")
rowInsert.append("INSERT INTO fornecedor (id, nome, razao_social, cnpj, inscricao_estadual, telefone, email, site, observacao, ativo, cep, rua, numero, bairro, cidade, estado, complemento) VALUES (4, 'Distribuidora de Teclados', 'Jonas Distribuidora de Teclados', '01.450.254/0001-52', '5 445 458 9', '41 3676 1510', 'jonasdt@bol.com', '', '', 1, '83430-000', 'Coronel Monteiro', '1450', 'Centro', 'Pinhais', 'PR', '')")
rowInsert.append("INSERT INTO fornecedor (id, nome, razao_social, cnpj, inscricao_estadual, telefone, email, site, observacao, ativo, cep, rua, numero, bairro, cidade, estado, complemento) VALUES (5, 'Distribuidora de Monitores', 'Rack Distribuidora de Monitores', '05.539.983/0001-52', '45 455 455 5', '41 3676 1854', 'rack@bol.com', 'www.rack.com.br', '', 1, '83430-000', 'Ernesto Kriger', '115', 'Centro', 'Pinhais', 'PR', '')")
rowInsert.append("INSERT INTO fornecedor (id, nome, razao_social, cnpj, inscricao_estadual, telefone, email, site, observacao, ativo, cep, rua, numero, bairro, cidade, estado, complemento) VALUES (6, 'Distribuidora de Informática Pichau', 'Pichau Distribuidora de Informática Ltda', '09.376.495/0001-22', '4 565 65456 6554', '41 36761510', 'pichau@bol.com', '', '', 1, '83430-000', 'Coronel Monteiro', '122', 'Centro', 'Campina Grande do Sul', 'PR', '')")
rowInsert.append("INSERT INTO fornecedor (id, nome, razao_social, cnpj, inscricao_estadual, telefone, email, site, observacao, ativo, cep, rua, numero, bairro, cidade, estado, complemento) VALUES (7, 'asd', 'asd', '05.570.714/0001-59', 'asdasd', '41', 'asd@bol.com.br', '', '', 0, '81050-580', 'Rua Dognor Cunha', '1450', 'Novo Mundo', 'Curitiba', 'PR', '')")

rowInsert.append("INSERT INTO cliente (id, nome, cpf, rg, telefone, email, observacao, ativo, cep, rua, numero, bairro, cidade, estado, complemento) VALUES (2, 'Marcos Aurélio Oripka', '783.626.959-00', '5.442.810-3', '41 9 8826 8276', 'oripka@bol.com', '', 1, '83430-000', 'Coronela Monteiro', '122', 'Centro', 'Campina Grande do Sul', 'PR', '')")
rowInsert.append("INSERT INTO cliente (id, nome, cpf, rg, telefone, email, observacao, ativo, cep, rua, numero, bairro, cidade, estado, complemento) VALUES (3, 'Vinicius Aurélio Oripka', '116.579.979-01', '14.273.390-0', '41 9 8826 8899', 'vini@bol.com', '', 1, '85890-000', 'Joéo dos Santos', '1600', 'Jardim California', 'Missal', 'PR', '')")
rowInsert.append("INSERT INTO cliente (id, nome, cpf, rg, telefone, email, observacao, ativo, cep, rua, numero, bairro, cidade, estado, complemento) VALUES (4, 'Amanda Larissa Oripka', '088.316.319-50', '12.864.704-0', '41 9 9826 8825', 'amanda@bol.com', '', 1, '83430-000', 'Ernesto Kriger', '115', 'Maria Antonieta', 'Pinhais', 'PR', '')")

rowInsert.append("INSERT INTO venda (id, observacao, data_emissao, data_entrega, data_vencimento, frete, total, desconto, cliente_id, forma_pagto_id) VALUES (1, '', '2024-05-21', '2024-05-21', '2024-05-21', 0, 16, 0, 4, 4)")
rowInsert.append("INSERT INTO venda (id, observacao, data_emissao, data_entrega, data_vencimento, frete, total, desconto, cliente_id, forma_pagto_id) VALUES (2, '', '2024-05-06', '2024-05-21', '2024-05-21', 0, 913.25, 0, 1, 2)")
rowInsert.append("INSERT INTO venda (id, observacao, data_emissao, data_entrega, data_vencimento, frete, total, desconto, cliente_id, forma_pagto_id) VALUES (3, '', '2024-05-07', '2024-05-21', '2024-05-21', 0, 1488.53, 0, 4, 3)")
rowInsert.append("INSERT INTO venda (id, observacao, data_emissao, data_entrega, data_vencimento, frete, total, desconto, cliente_id, forma_pagto_id) VALUES (4, '', '2024-05-10', '2024-05-21', '2024-05-21', 0, 1148.25, 0, 2, 1)")

rowInsert.append("INSERT INTO venda_item (id, qtde, preco, venda_id, produto_id) VALUES (1, 1, 8, 1, 15)")
rowInsert.append("INSERT INTO venda_item (id, qtde, preco, venda_id, produto_id) VALUES (2, 1, 5, 1, 3)")
rowInsert.append("INSERT INTO venda_item (id, qtde, preco, venda_id, produto_id) VALUES (3, 1, 3, 1, 5)")
rowInsert.append("INSERT INTO venda_item (id, qtde, preco, venda_id, produto_id) VALUES (4, 1, 8, 2, 15)")
rowInsert.append("INSERT INTO venda_item (id, qtde, preco, venda_id, produto_id) VALUES (6, 1, 415.25, 2, 10)")
rowInsert.append("INSERT INTO venda_item (id, qtde, preco, venda_id, produto_id) VALUES (7, 1, 5, 3, 3)")
rowInsert.append("INSERT INTO venda_item (id, qtde, preco, venda_id, produto_id) VALUES (8, 1, 753.53, 3, 4)")
rowInsert.append("INSERT INTO venda_item (id, qtde, preco, venda_id, produto_id) VALUES (9, 1, 730, 3, 14)")
rowInsert.append("INSERT INTO venda_item (id, qtde, preco, venda_id, produto_id) VALUES (10, 1, 730, 4, 14)")
rowInsert.append("INSERT INTO venda_item (id, qtde, preco, venda_id, produto_id) VALUES (11, 1, 415.25, 4, 10)")
rowInsert.append("INSERT INTO venda_item (id, qtde, preco, venda_id, produto_id) VALUES (12, 1, 3, 4, 9)")

rowInsert.append("INSERT INTO compra (id, nro_nota, observacao, data_emissao, data_entrega, data_vencimento, frete, total, desconto, fornecedor_id, forma_pagto_id) VALUES (1, '1000', '', '2024-05-21', '2024-05-21', '2024-05-21', 0, 7350, 0, 5, 3)")
rowInsert.append("INSERT INTO compra (id, nro_nota, observacao, data_emissao, data_entrega, data_vencimento, frete, total, desconto, fornecedor_id, forma_pagto_id) VALUES (2, '3500', '', '2024-05-21', '2024-05-21', '2024-05-21', 0, 111, 0, 5, 3)")
rowInsert.append("INSERT INTO compra (id, nro_nota, observacao, data_emissao, data_entrega, data_vencimento, frete, total, desconto, fornecedor_id, forma_pagto_id) VALUES (3, '4500', '', '2024-05-21', '2024-05-21', '2024-05-21', 0, 216, 0, 1, 3)")
rowInsert.append("INSERT INTO compra (id, nro_nota, observacao, data_emissao, data_entrega, data_vencimento, frete, total, desconto, fornecedor_id, forma_pagto_id) VALUES (4, '8000', '', '2024-05-21', '2024-05-21', '2024-05-21', 0, 124, 0, 3, 3)")
rowInsert.append("INSERT INTO compra (id, nro_nota, observacao, data_emissao, data_entrega, data_vencimento, frete, total, desconto, fornecedor_id, forma_pagto_id) VALUES (5, '100', '', '2024-05-10', '2024-05-21', '2024-05-21', 0, 111, 0, 3, 3)")
rowInsert.append("INSERT INTO compra (id, nro_nota, observacao, data_emissao, data_entrega, data_vencimento, frete, total, desconto, fornecedor_id, forma_pagto_id) VALUES (6, '200', '', '2024-05-15', '2024-05-21', '2024-05-21', 0, 45, 0, 4, 4)")

rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (1, 10, 350, 1, 15)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (2, 10, 385, 1, 5)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (3, 1, 5, 2, 15)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (4, 1, 5, 2, 3)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (5, 1, 5, 2, 5)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (6, 1, 5, 2, 1)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (7, 1, 6, 2, 4)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (8, 1, 5, 2, 2)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (9, 1, 5, 2, 14)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (10, 1, 5, 2, 10)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (11, 2, 10, 2, 16)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (12, 5, 10, 2, 7)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (13, 2, 8, 3, 15)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (14, 5, 11, 3, 3)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (15, 4, 7, 3, 5)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (16, 5, 7, 3, 4)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (17, 3, 7, 3, 2)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (18, 2, 4, 3, 14)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (19, 5, 6, 3, 10)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (20, 3, 5, 3, 16)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (21, 2, 4, 3, 7)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (22, 1, 3, 4, 15)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (23, 2, 4, 4, 3)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (24, 3, 5, 4, 5)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (25, 4, 6, 4, 1)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (26, 5, 5, 4, 4)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (27, 3, 8, 4, 14)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (28, 5, 5, 4, 10)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (29, 9, 7, 5, 3)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (30, 3, 6, 5, 5)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (31, 3, 10, 5, 10)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (32, 3, 10, 6, 3)")
rowInsert.append("INSERT INTO compra_item (id, qtde, preco, compra_id, produto_id) VALUES (33, 3, 5, 6, 5)")


rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (1, 'Recebimento diverso', '4/2024 Parcela 1 de 5.', '1000', 'Aberto', '2024-05-21', '2024-05-21', 1500, 300, 295, NULL, 1, NULL, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (2, 'Recebimento diverso', '5/2024 Parcela 2 de 5.', '1000', 'Pago', '2024-06-21', '2024-05-21', 1500, 300, 300, NULL, 1, NULL, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (3, 'Recebimento diverso', '6/2024 Parcela 3 de 5.', '1000', 'Pago', '2024-07-21', '2024-05-22', 1500, 300, 300, NULL, 1, NULL, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (4, 'Recebimento diverso', '7/2024 Parcela 4 de 5.', '1000', 'Pago', '2024-08-21', '2024-05-21', 1500, 300, 300, NULL, 1, NULL, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (5, 'Recebimento diverso', '8/2024 Parcela 5 de 5.', '1000', 'Pago', '2024-09-21', '2024-05-22', 1500, 300, 300, NULL, 1, 1, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (6, 'Recebimento Cliente: José Elias', '4/2024 Parcela 1 de 2.', '1', 'Aberto', '2024-05-21', '2024-05-21', 16, 8, 5, 1, 4, NULL, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (7, 'Recebimento Cliente: José Elias', '5/2024 Parcela 2 de 2.', '1', 'Aberto', '2024-06-21', '2024-06-21', 16, 8, 0, 1, 4, NULL, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (8, 'Recebimento Cliente: Marcos Aurélio Oripk', '4/2024 Parcela 1 de 2.', '2', 'Aberto', '2024-05-21', '2024-05-21', 913.25, 456.62, 0, 2, 1, NULL, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (9, 'Recebimento Cliente: Marcos Aurélio Oripk', '5/2024 Parcela 2 de 2.', '2', 'Aberto', '2024-06-21', '2024-06-21', 913.25, 456.62, 0, 2, 1, NULL, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (10, 'Recebimento Cliente: José Elias', '4/2024 Parcela 1 de 3.', '3', 'Aberto', '2024-05-21', '2024-05-21', 1488.53, 496.18, 0, 3, 4, NULL, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (11, 'Recebimento Cliente: José Elias', '5/2024 Parcela 2 de 3.', '3', 'Aberto', '2024-06-21', '2024-06-21', 1488.53, 496.18, 0, 3, 4, NULL, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (12, 'Recebimento Cliente: José Elias', '6/2024 Parcela 3 de 3.', '3', 'Aberto', '2024-07-21', '2024-07-21', 1488.53, 496.18, 0, 3, 4, NULL, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (13, 'Recebimento Cliente: Vinicius Aurélio Ori', '4/2024 Parcela 1 de 2.', '4', 'Pago', '2024-05-21', '2024-05-22', 1148.25, 574.12, 574.12, 4, 2, 4, 2)")
rowInsert.append("INSERT INTO conta_receber (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, venda_id, cliente_id, forma_pagto_id, centro_custo_id) VALUES (14, 'Recebimento Cliente: Vinicius Aurélio Ori', '5/2024 Parcela 2 de 2.', '4', 'Aberto', '2024-06-21', '2024-06-21', 1148.25, 574.12, 0, 4, 2, NULL, 2)")

rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (2, 'Pagamentos Diversos', '4/2024 Parcela 1 de 1.', '2500', 'Aberto', '2024-05-20', NULL, 2000, 2000, 0, NULL, 3, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (3, 'Pagamento Manutenééo', '4/2024 Parcela 1 de 3.', '1000', 'Aberto', '2024-05-20', NULL, 600, 200, 0, NULL, 4, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (4, 'Pagamento Manutenééo', '5/2024 Parcela 2 de 3.', '1000', 'Aberto', '2024-06-20', NULL, 600, 200, 0, NULL, 4, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (5, 'Pagamento Manutenééo', '6/2024 Parcela 3 de 3.', '1000', 'Pago', '2024-07-20', '2024-05-21', 600, 200, 200, NULL, 4, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (6, 'Pagto Fornec: Distribuidora de Inf', '4/2024 Parcela 1 de 2.', '1000', 'Aberto', '2024-05-21', '2024-05-21', 7350, 3675, 0, 1, 5, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (7, 'Pagto Fornec: Distribuidora de Inf', '5/2024 Parcela 2 de 2.', '1000', 'Pago', '2024-06-21', '2024-05-22', 7350, 3675, 3675, 1, 5, 1, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (8, 'Pagto Fornec: Distribuidora de Pen', '4/2024 Parcela 1 de 2.', '4500', 'Aberto', '2024-05-21', '2024-05-21', 216, 108, 0, 3, 1, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (9, 'Pagto Fornec: Distribuidora de Pen', '5/2024 Parcela 2 de 2.', '4500', 'Aberto', '2024-06-21', '2024-06-21', 216, 108, 0, 3, 1, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (10, 'Pagto Fornec: Distribuidora de Tec', '4/2024 Parcela 1 de 2.', '8000', 'Aberto', '2024-05-21', '2024-05-21', 124, 62, 0, 4, 3, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (11, 'Pagto Fornec: Distribuidora de Tec', '5/2024 Parcela 2 de 2.', '8000', 'Aberto', '2024-06-21', '2024-06-21', 124, 62, 0, 4, 3, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (12, 'Pagto Fornec: Distribuidora de Tec', '4/2024 Parcela 1 de 2.', '100', 'Pago', '2024-05-21', '2024-05-21', 111, 55.5, 55.5, 5, 3, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (13, 'Pagto Fornec: Distribuidora de Tec', '5/2024 Parcela 2 de 2.', '100', 'Pago', '2024-06-21', '2024-05-21', 111, 55.5, 55.5, 5, 3, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (14, 'Pagto Fornec: Distribuidora de Mon', '4/2024 Parcela 1 de 3.', '200', 'Aberto', '2024-05-21', '2024-05-21', 45, 15, 0, 6, 4, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (15, 'Pagto Fornec: Distribuidora de Mon', '5/2024 Parcela 2 de 3.', '200', 'Aberto', '2024-06-21', '2024-06-21', 45, 15, 0, 6, 4, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (16, 'Pagto Fornec: Distribuidora de Mon', '6/2024 Parcela 3 de 3.', '200', 'Pago', '2024-07-21', '2024-05-22', 45, 15, 15, 6, 4, 3, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (17, 'Pagto diverso', '4/2024 Parcela 1 de 2.', '1600', 'Pago', '2024-05-06', '2024-05-21', 55, 27.5, 27.5, NULL, 3, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (18, 'Pagto diverso', '5/2024 Parcela 2 de 2.', '1600', 'Aberto', '2024-06-06', NULL, 55, 27.5, 0, NULL, 3, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (19, 'Pagto diversos', '4/2024 Parcela 1 de 3.', '1300', 'Aberto', '2024-05-10', NULL, 88, 29.33, 0, NULL, 4, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (20, 'Pagto diversos', '5/2024 Parcela 2 de 3.', '1300', 'Aberto', '2024-06-10', NULL, 88, 29.33, 0, NULL, 4, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (21, 'Pagto diversos', '6/2024 Parcela 3 de 3.', '1300', 'Aberto', '2024-07-10', NULL, 88, 29.33, 0, NULL, 4, NULL, 1)")
rowInsert.append("INSERT INTO conta_pagar (id, descricao, referencia, doc_numero, status, data_vcto, data_pagto, valor_titulo, valor_parcela, valor_pago, compra_id, fornecedor_id, forma_pagto_id, centro_custo_id) VALUES (22, 'Pagamento diverso', '5/2024 Parcela 1 de 1.', '10', 'Aberto', '2024-06-20', NULL, 350, 350, 0, NULL, 3, NULL, 1)")



# create all table app
def populate_tables():
    conn, cursor = db()

    for row in rowInsert:
        cursor.execute(row)

    conn.commit()
    conn.close()

populate_tables()